### ISSUE TITLE
this package is not supported for laravel 7.can u please provide one for laravel 7

### ISSUE THREAD

**Issue by aleeshanoushad** [designmynight/laravel-mongodb-passport#40]
![image](https://user-images.githubusercontent.com/20252109/80446688-24afe280-8935-11ea-978d-d803cb14b729.png)
this is what happening when i try to install this package

**Comment by a-zog** [comment]
Any updates regarding this issue please?

**Comment by aleeshanoushad** [comment]
> Any updates regarding this issue please?

no yet

**Comment by SaeedNikmehr** [comment]
i have the same problem . for laravel 7 i had to use jens segers/mongo db version 4.* . but it seems this package can only work with v3.6 or less than that . so any one has any idea how fix this problem to use passport in laravel with mongo?

**Comment by alasdairmackenzie** [comment]
Can you make a PR to resolve this?

**Comment by SaeedNikmehr** [comment]
> Can you make a PR to resolve this?

it seems this error  happens because passport still use Illuminate\Database\Eloquent\Model instead of  Jenssegers\Mongodb\Eloquent\Model
so after install jenssegers/laravel you can replace them in vendor files .
i found these :
/vendor/laravel/passport/src/AuthCode.php
/vendor/laravel/passport/src/Client.php
/vendor/laravel/passport/src/PersonalAccessClient.php
/vendor/laravel/passport/src/RefreshToken.php
/vendor/laravel/passport/src/Token.php
also check this 
https://github.com/sadnub/laravel-mongodb-passport-fix

**Comment by alasdairmackenzie** [comment]
Thanks for that - that looks good. I'll have a look tomorrow at those changes. If you can make a PR with those changes then that'll help me out.

**Comment by mykeysr** [comment]
Any update please?

**Comment by hypnodev** [comment]
I've released PR #46 that with some upgrade of some dependencies make it's usable also in 7

**Comment by a-zog** [comment]
Seems that the issue is not resolved yet.

I'd like to thank the #DesignMyNight team for the great work it has done to make our lives easier.

At the same time, Laravel releases are out at a very faster pace and this package is holding our technical capabilities back.

Would you please tell us more about the challenges that are preventing you from making this 📦 available to L7 or even L8? How can this community help you go faster?

Thank you in advance

**Comment by tatyanakoba** [comment]
Hi guys, do you plan to upgrade package for new laravel version?
